services:
  # Frontend React
  frontend:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://ia.encnetwork.com.br:8001
    restart: unless-stopped
    depends_on:
      - backend

  # Backend Python
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_UPLOAD_MB=300
      - OPENAI_MODEL=gpt-4o
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    restart: unless-stopped