services:
  # Frontend React (com nginx proxy)
  frontend:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - translator-network

  # Backend Python
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_UPLOAD_MB=300
      - OPENAI_MODEL=gpt-5-2025-08-07
      - MODEL_NORMAL=gpt-5-2025-08-07
      - MODEL_RAPIDO=gpt-5-mini-2025-08-07
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/backups:/app/backups
    restart: unless-stopped
    networks:
      - translator-network

networks:
  translator-network:
    driver: bridge