services:
  # Frontend React (com nginx proxy)
  frontend:
    build: .
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - translator-network

  # Backend Python
  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_UPLOAD_MB=300
      - OPENAI_MODEL=gpt-4o
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
    restart: unless-stopped
    networks:
      - translator-network

networks:
  translator-network:
    driver: bridge